In [1]:
%load_ext autoreload
%autoreload 2

In [2]:
import numpy as np
from scipy.interpolate import interp1d

In [3]:
from format_convert import *
from feature_extraction import *

In [17]:
file_location = '../data-raw'
patient_id = '041602jb'
trial = 1

In [18]:
df = trcToCSV(file_location, patient_id, trial)
df.head()

  frame#   time head vertex                         right ear             \
                          X          Y           Z          X          Y
1    1.0  0.000   343.75946  245.51552  1728.31689  397.63239  148.26811
2    2.0  0.008   343.75946  245.51552  1728.31689  397.63239  148.26811
3    3.0  0.017   344.03885  245.52298  1728.36243  397.91818  148.22864
4    4.0  0.025   344.03885  245.52298  1728.36243  397.91818  148.22864
5    5.0  0.033   344.03885  245.52298  1728.36243  398.04483  148.54829

                left ear             ... left mth     slider            \
            Z          X          Y  ...        Z          X         Y
1  1622.74231  395.71133  360.56482  ...  3.03345  965.91101 -21.14479
2  1622.74231  395.69720  360.99396  ...  3.03345  965.67474 -21.40953
3  1622.92114  396.36719  361.41528  ...  2.67758  965.91101 -21.14479
4  1622.92114  396.36719  361.41528  ...  2.67758  965.91101 -21.14479
5  1622.88379  396.36719  361.41528  ...  2.92389  965.91101 -21.14479

               fixed 1                      fixed 2
         Z           X         Y         Z        X        Y        Z
1  9.93127  1955.65491 -11.80660 -14.00936 -4.60406  1.00681  9.24365
2  9.74698  1956.15808 -11.79542 -13.62272 -4.28350  0.95118  8.98660
3  9.93127  1955.65491 -11.80660 -14.00936 -4.28350  0.95118  8.98660
4  9.93127  1955.65491 -11.80660 -14.00936 -4.28350  0.95118  8.98660
5  9.93127  1955.65491 -11.80660 -14.00936 -4.28350  0.95118  8.98660

[5 rows x 86 columns]

In [25]:
file_location = '../data-raw'
patient_id = '022318xz'
trial = 4

In [26]:
df = matToCSV(file_location, patient_id, trial)
df.head()

  frame#      time     RSlider                           Lslider              \
                             X          Y          Z           X           Y
0      1  0.000000  984.617126  39.416691  79.357513  963.309998  652.304565
1      2  0.006667  984.435181  39.965942  79.637100  963.055542  652.503784
2      3  0.013333  984.437439  39.988850  79.663651  963.011780  652.505249
3      4  0.020000  984.760559  40.009857  79.557877  963.172852  652.505249
4      5  0.026667  984.766968  40.022362  79.580284  963.174927  652.523682

                    Fix 2             ...    Rt.wrist Lt.shoulder              \
           Z            X          Y  ...           Z           X           Y
0  76.069817  2487.009033 -22.823305  ...  853.884399 -972.569763  589.671509
1  75.885750  2487.018799 -22.792938  ...  853.964661 -966.161682  587.210022
2  75.886986  2487.027100 -22.846186  ...  853.968628 -965.762146  587.024292
3  76.070160  2486.892334 -22.950426  ...  853.547302 -972.385376  589.745605
4  76.082802  2486.851074 -22.950968  ...  853.559692 -972.409485  589.556396

                  Lt.elbow                            Lt.wrist              \
             Z           X           Y           Z           X           Y
0  1211.283203 -966.540283  656.029358  984.180847 -888.710693  630.705261
1  1210.581177 -966.477234  655.984192  984.227356 -888.163879  630.567444
2  1210.597290 -966.384460  655.960571  984.280945 -888.320129  630.548401
3  1211.141113 -966.476440  655.919861  984.228333 -888.329590  630.350952
4  1211.227539 -966.500793  655.905151  984.285767 -888.174622  630.328247


            Z
0  840.042542
1  840.249573
2  840.233582
3  840.277222
4  840.287048

[5 rows x 92 columns]

In [27]:
df = c3dToCSV(file_location, patient_id, trial) # convert c3d to pandas df, save to csv. two steps
df.head()

  frame#      time     RSlider                           Lslider              \
                             X          Y          Z           X           Y
0      1  0.000000  984.617126  39.416691  79.357513  963.309998  652.304565
1      2  0.006667  984.435181  39.965942  79.637100  963.055542  652.503784
2      3  0.013333  984.437439  39.988850  79.663651  963.011780  652.505249
3      4  0.020000  984.760559  40.009857  79.557877  963.172852  652.505249
4      5  0.026667  984.766968  40.022362  79.580284  963.174927  652.523682

                    Fix 2             ...    Rt.wrist Lt.shoulder              \
           Z            X          Y  ...           Z           X           Y
0  76.069817  2487.009033 -22.823305  ...  853.884399 -972.569763  589.671509
1  75.885750  2487.018799 -22.792938  ...  853.964661 -966.161682  587.210022
2  75.886986  2487.027100 -22.846186  ...  853.968628 -965.762146  587.024292
3  76.070160  2486.892334 -22.950426  ...  853.547302 -972.385376  589.745605
4  76.082802  2486.851074 -22.950968  ...  853.559692 -972.409485  589.556396

                  Lt.elbow                            Lt.wrist              \
             Z           X           Y           Z           X           Y
0  1211.283203 -966.540283  656.029358  984.180847 -888.710693  630.705261
1  1210.581177 -966.477234  655.984192  984.227356 -888.163879  630.567444
2  1210.597290 -966.384460  655.960571  984.280945 -888.320129  630.548401
3  1211.141113 -966.476440  655.919861  984.228333 -888.329590  630.350952
4  1211.227539 -966.500793  655.905151  984.285767 -888.174622  630.328247


            Z
0  840.042542
1  840.249573
2  840.233582
3  840.277222
4  840.287048

[5 rows x 92 columns]

In [28]:
df = motionToJointAngle(file_location, patient_id, trial, save=True)
df.head()

Columns in CSV            Mapped Column
______________            _____________
Lt.heel                   Left heel
Rt.heel                   Right heel
Lt.toe                    Left toe
Rt.toe                    Right toe
Lt.knee                   Left knee
Rt.knee                   Right knee
Lt.ankle                  Left ankle
Rt.Ankle                  Right ankle
Lt.hip                    Left hip
Rt.hip                    Right hip
Lt.shoulder               Left shoulder
Rt.shoulder               Right shoulder

,time,#frame,Rfoot,Lfoot,Rshank,Lshank,Rthigh,Lthigh,Trunk
0,0.0,1,176.887094,-179.714986,82.885544,85.256547,79.588158,NaN,NaN
1,0.006666666666666667,2,177.060975,-179.737336,82.788236,85.242994,79.711945,NaN,NaN
2,0.013333333333333334,3,177.076345,-179.733176,82.786878,85.256767,79.710037,NaN,NaN
3,0.02,4,177.550355,-179.727837,83.033498,85.917125,79.666922,NaN,NaN
4,0.02666666666666667,5,177.549562,-179.733118,83.046465,85.918616,79.664594,NaN,NaN

In [ ]:
# Load to data-processed 082119sm0013

In [14]:
file_location = '../data-processed/healthy_controls/'
pid = '081517ap'
get_stp_params(file_location, pid, save = False)

,sid,trial,RstepLength,LstepLength,timeRswing,timeLswing,timeRgait,timeLgait,GaitSpeed
0,081517ap,8,1.344197,1.377824,0.7534,0.6933,1.1200,1.115,1.115111
1,081517ap,9,1.500711,1.220891,0.7417,0.7500,1.0733,1.115,1.121815

In [ ]:
subject = '081517ap'
trial = 8
trialtype = 'Nat'
cycle = 'L'

file_location = 'C:/Users/qshah/Documents/Spring 2024/eMoGis/data-processed/healthy_controls'
data_type = 'jnt'

In [ ]:
# plot(subject, trial, file_location, data_type)

In [ ]:
# Mark step times

# L = [(2.8333,3.6433), (4.15,4.8417)]
# R = [(3.455,4.3033), (4.675,5.44)]

# mark_step_times(L, R, file_location, subject, trial, trialtype)

In [ ]:
# grf, jnt = normalize_data(file_location, subject, trial, cycle, data_type)

### Images for Teaser Image

In [15]:
# from PyGait.format_convert import *
# from PyGait.feature_extraction import *

In [ ]:
# df_raw_trajectory = c3dToCSV('data/input/022318xz0004.c3d')
# df_grf = pd.read_csv('data/input/022318xz0004.csv')

# df_raw_trajectory = impute_missing_values(df_raw_trajectory)
# df_grf = impute_missing_values(df_grf)

# df_raw_trajectory = filter_noise(df_raw_trajectory, 'bandpass')
# df_grf = filter_noise(df_grf, 'bandpass')

In [ ]:
# df_angle = motionToJointAngle(df)
# df_moment = computeJointMoment(df_angle, df_grf)
# df_spatiotemporal = extractSpatiotemporal(df_grf)

In [ ]:
# mark_step_times(df_grf)

In [ ]:
# df_angle = normalizeByGaitCycle(df_angle)

In [ ]:
# createPatientGroup('Healthy Adults')

# patient_id = '022318'
# trial_id = '022318xz0004'

# upload_data('Healthy Adults', patient_id, trial_id)

In [ ]:
# predictFallRisk(df_raw_trajectory, df_angle, df_grf)

### Images for Teaser Image (End) **